### ISSUE TITLE
A listagem de algumas coisas está dando fatal error

### ISSUE THREAD

**Issue by MarcoWorms** [pagarme/pagarme-php#181]
## Contexto

Tentei listar minhas transações e tive um erro inesperado que veio de dentro da lib. A listagem de balanceOperations e payables também dão o mesmo erro.

```
<?php

require('vendor/autoload.php');


$apiKey = 'minha_ak';
$pagarMe =  new \PagarMe\Sdk\PagarMe($apiKey);
$transactionList = $pagarMe->transaction()->getList();

var_dump($transactionList);
```

## Ambiente

tentei com as versões 5.4.45 e 5.6.30 do PHP
Mac OS 10.12.4

composer.json
```
{
  "require": {
    "pagarme-php": "^3.2"
  }
}
```

## Passos para reproduzir

Instale a lib com o composer e cole o código acima e trocando 'minha_ak' por uma API key válida.

## Resultado esperado

Minha lista de transações

## Resultado atual

```
PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.' in /Users/marcoworms/Documents/php/vendor/pagarme/pagarme-php/lib/Transaction/TransactionBuilder.php:25
Stack trace:
#0 /Users/marcoworms/Documents/php/vendor/pagarme/pagarme-php/lib/Transaction/TransactionBuilder.php(25): DateTime->__construct('2017-03-30T20:3...')
#1 /Users/marcoworms/Documents/php/vendor/pagarme/pagarme-php/lib/Transaction/TransactionHandler.php(125): PagarMe\Sdk\Transaction\TransactionHandler->buildTransaction(Object(stdClass))
#2 /Users/marcoworms/Documents/php/index.php(8): PagarMe\Sdk\Transaction\TransactionHandler->getList()
#3 {main}
  thrown in /Users/marcoworms/Documents/php/vendor/pagarme/pagarme-php/lib/Transaction/TransactionBuilder.php on line 25

Fatal error: Uncaught exception 'Exception' with message 'DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.' in /Users/marcoworms/Documents/php/vendor/pagarme/pagarme-php/lib/Transaction/TransactionBuilder.php:25
Stack trace:
#0 /Users/marcoworms/Documents/php/vendor/pagarme/pagarme-php/lib/Transaction/TransactionBuilder.php(25): DateTime->__construct('2017-03-30T20:3...')
#1 /Users/marcoworms/Documents/php/vendor/pagarme/pagarme-php/lib/Transaction/TransactionHandler.php(125): PagarMe\Sdk\Transaction\TransactionHandler->buildTransaction(Object(stdClass))
#2 /Users/marcoworms/Documents/php/index.php(8): PagarMe\Sdk\Transaction\TransactionHandler->getList()
#3 {main}
  thrown in /Users/marcoworms/Documents/php/vendor/pagarme/pagarme-php/lib/Transaction/TransactionBuilder.php on line 25
```

**Comment by MarcoWorms** [comment]
Corrigido, o problema era a falta do setup da date_timezone. Se alguém mais tiver o mesmo problema e só colocar essa linha no código:

```php
date_default_timezone_set('America/Sao_Paulo');
```

O código final ficaria assim:

```php
<?php

require('vendor/autoload.php');


date_default_timezone_set('America/Sao_Paulo');

$apiKey = 'minha_ak';
$pagarMe =  new \PagarMe\Sdk\PagarMe($apiKey);
$transactionList = $pagarMe->transaction()->getList();

var_dump($transactionList);
```
