### ISSUE TITLE
Erro 403 fordidden (error code: 1020) ao tentar realizar uma transação

### ISSUE THREAD

**Issue by jhoow** [pagarme/pagarme-php#361]
## Contexto

Olá pessoal, tudo bem? Estou tendo problemas ao tentar realizar qualquer operacao (criacao de transacao, cartão, assinatura, por exemplo) com a api V4 (já tentei também alterar para v3 e v2) e a ultima lib pagarme-php. 

## Ambiente

[caso essa issue se trate de um bug, descreva como é o ambiente que ele ocorre, por exemplo:]

* SDK Pagar.me 0.1.6
* Servidor Linux
* PHP 5.6 (tambem testado com 7.1 e 7.2)
* Apache 2.2
* MySQL 5.6
* Qualquer outra característica a ser considerada

## Passos para reproduzir

Ao tentar utilizar, por exemplo, $transaction = $pagarme->transactions()->create($arrayTransacao); ... também para criacao de cartão por exemplo.

Me retorna este erro:
Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://api.pagar.me/1/transactions?api_key=ak_test_hk6gJXLVVKFGrwcIthEI2OaKRwOe9l` resulted in a `403 Forbidden` response: error code: 1020 in /home/quanntummcom/public_html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113 Stack trace: #0 /home/quanntummcom/public_html/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 /home/quanntummcom/public_html/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 /home/quanntummcom/public_html/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3 /home/quanntummcom/public_html/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #4 /home/quanntummcom/public_html/ven in /home/quanntummcom/public_html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113

## Resultado esperado

É esperado o sucesso na criação da transação. Um teste simples com o aplicativo Insomnia/Postman retorna sucesso com os mesmos dados.

## Resultado atual

Erro 403

## Possível correção

Talvez indicar uma tabela com os codigos de erros atualizados, não encontrei na documentação este codigo.

Obrigado!

**Comment by curtinaz** [comment]
Retirei o objeto billing inteiro, e funcionou
