### ISSUE TITLE
Erro crítico ao cadastrar recebedor Pagarme

### ISSUE THREAD

**Issue by khairalla86** [pagarme/pagarme-php#396]
Ao tentar cadastrar um lojista com endereço e dados bancários, recebo um erro crítico:
OBS: A conta é cadastrada na pagar.me e no banco de dados, mas ao tentar inserir o recebedor na pagar.me o erro ocorre.

022-02-27T13:40:43+00:00 CRITICAL Uncaught PagarMe\Sdk\ClientException: {"errors":[{"type":"not_found","parameter_name":"id","message":"BankAccount não encontrado"}],"url":"/bank_accounts/10031695","method":"get"} in PagarMeDokan/vendor/pagarme/pagarme-php/lib/Client.php:68
Stack trace:
#0 PagarMeDokan/vendor/pagarme/pagarme-php/lib/BankAccount/BankAccountHandler.php(74): PagarMe\Sdk\Client->send(Object(PagarMe\Sdk\BankAccount\Request\BankAccountGet))
#1 PagarMeDokan/pagarme_dokan.php(768): PagarMe\Sdk\BankAccount\BankAccountHandler->get('10031695')
#2 wp-includes/class-wp-hook.php(307): salvar_dados_bancarios(Object(WeDevs\Dokan\Vendor\SetupWizard))
#3 wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#4 wp-includes/plugin.php(474): WP_Hook->do_action(A, em PagarMeDokan/vendor/pagarme/pagarme-php/lib/Client.php, na linha 68

**Client.php linha 68:**

 catch (\GuzzleHttp\Exception\ClientException $exception) {
            $message = $exception->getResponse()->getBody()->getContents();
            $code = $exception->getResponse()->getStatusCode();
            throw new ClientException($message, $code);

Se alguém já passou por isso e puder ajudar, eu agradeço!

**Comment by santanamic** [comment]
Adicione o seguinte código antes de retornar uma [conta bancaria recém criada](https://github.com/pagarme/pagarme-php#retornando-uma-conta-banc%C3%A1ria) na pagar.me pelo ID
`sleep(5);`

Parece que a API agora tem um delay na listagem das contas bancarias recém criadas. Portanto a conta passado não é encontrada de imediato, oque leva ao erro.
